%% Getting the triple point contact line
% Author: Vatsal Sanjay
% vatsalsanjay@gmail.com
% Physics of Fluids
clc
clear
close
%% getting all variables
% Popinet's Augumented Lagrangian Calculations
load('Popinet_AugumentedLagrangian.mat');
% Vola Et al. 2003
load('VolaEtAl.mat');
nskip = 2;
% 
filename = {'tau0'; 'tau1'; 'tau2'; 'tau3'; 'tau4'};
Bas = {[]};
for counter = 1:1:length(filename)
    ll=evalc(sprintf('!./getDataLine %s', filename{counter}));
    bolo=textscan(ll,'%f %f\n');
    Bas{counter}.y = bolo{1}+0.5; Bas{counter}.u = bolo{2}; 
end

figure1 = figure('visible','on','WindowState','fullscreen','Color',[1 1 1]);
axes1 = axes('Parent',figure1);
hold(axes1,'on');
COLOR = lines(length(filename));

for counter = 1:1:length(filename)
    plot(ALM{counter}.y(2:nskip:end),ALM{counter}.u(2:nskip:end),'.','color',COLOR(counter,:),'MarkerSize',40,'LineWidth',2)
    plot(Vola{counter}.y,Vola{counter}.u,'+','color',COLOR(counter,:),'MarkerSize',20,'LineWidth',2)
    plot(Bas{counter}.y,Bas{counter}.u,'-','color',COLOR(counter,:),'MarkerSize',40,'LineWidth',3)
end
colormap(lines(length(filename)))
caxis([0 1.0])
colorbar('Ticks',[0.10,0.30,0.50,0.70,0.90],...
         'TickLabels',{'\boldmath{$\tau_y = 0$}','\boldmath{$\tau_y = 1/\sqrt{2}$}','\boldmath{$\tau_y = 10/\sqrt{2}$}',...
         '\boldmath{$\tau_y = 100/\sqrt{2}$}','\boldmath{$\tau_y = 1000/\sqrt{2}$}'},...
         'TickLabelInterpreter','latex')
     
box(axes1,'on');
set(axes1,'DataAspectRatio',[1 1 1],'FontName','times new roman','FontSize',...
    30,'FontWeight','bold','LineWidth',3,'PlotBoxAspectRatio',[1 1 1]);

xlim([0.0 1.0])
ylim([-0.4 1.0])
axis square

xlabel('\boldmath{$y$}','LineWidth',2,'FontWeight','bold','FontSize',50,...
            'FontName','times new roman',...
            'Interpreter','latex');
ylabel('\boldmath{$u$}','LineWidth',2,'FontWeight','bold','FontSize',50,...
    'FontName','times new roman',...
    'Interpreter','latex'); 


% Create line (Basilisk Data)
annotation(figure1,'line',[0.36 0.38],...
    [0.70 0.70],'LineWidth',3);
annotation(figure1,'textbox',...
    [0.384214285714286 0.680066445182723 0.225 0.0375],...
    'String','\textbf{Current Simulation (Basilisk C)}',...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',24,...
    'FitBoxToText','off',...
    'EdgeColor','none');

% Create Plus (Vola et al.)
annotation(figure1,'line',[0.36 0.38],...
    [0.75 0.75],'LineWidth',3);
annotation(figure1,'line',[0.37 0.37],...
    [0.735 0.765],'LineWidth',3);
annotation(figure1,'textbox',...
    [0.384404761904762 0.730001001001001 0.123214285714286 0.038],...
    'String','\textbf{Vola et al. (2003)}',...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',24,...
    'FitBoxToText','off',...
    'EdgeColor','none');


% Create Circle (Augumented Lagrangian Method)
annotation(figure1,'ellipse',...
    [0.3625 0.80 0.014 0.024],...
    'LineWidth',2,...
    'FaceColor',[0 0 0]);
annotation(figure1,'textbox',...
    [0.38 0.788482834994463 0.240071428571429 0.0387596899224795],...
    'String','\textbf{Augumented Lagrangian Method}',...
    'Interpreter','latex',...
    'HorizontalAlignment','center',...
    'FontWeight','bold',...
    'FontSize',24,...
    'FitBoxToText','off',...
    'EdgeColor','none');



